// types for bus travel 

export const LOAD_CITIES_SCCESSE = "LOAD_CITIES_SCCESSE"
export const GET_CITIES_SCCESSE = "GET_CITIES_SCCESSE"
export const FAILD_CITIES_SCCESSE = "FAILD_CITIES_SCCESSE"


export const LOAD_SEARCH = "LOAD_SEARCH"
export const GET_SEARCH = "GET_SEARCH"
export const FAILD_SEARCH = "FAILD_SEARCH"

export const LOAD_SINGLE_TRIP = "LOAD_SINGLE_TRIP" 
export const GET_SINGLE_TRIP = "GET_SINGLE_TRIP"
export const FAILD_SINGLE_TRIP = "FAILD_SINGLE_TRIP"

export const LOAD_AVIALBLE_SEATS = "LOAD_AVIALBLE_SEATS" 
export const GET_AVIALBLE_SEATS = "GET_AVIALBLE_SEATS"
export const FAILD_AVIALBLE_SEATS = "FAILD_AVIALBLE_SEATS"