// types for bus travel 

export const LOAD_CITIES_SCCESSE = "LOAD_CITIES_SCCESSE"
export const GET_CITIES_SCCESSE = "GET_CITIES_SCCESSE"
export const FAILD_CITIES_SCCESSE = "FAILD_CITIES_SCCESSE"


export const LOAD_SEARCH = "LOAD_SEARCH"
export const GET_SEARCH = "GET_SEARCH"
export const FAILD_SEARCH = "FAILD_SEARCH"

export const LOAD_SINGLE_TRIP = "LOAD_SINGLE_TRIP" 
export const GET_SINGLE_TRIP = "GET_SINGLE_TRIP"
export const FAILD_SINGLE_TRIP = "FAILD_SINGLE_TRIP"

export const LOAD_AVIALBLE_SEATS = "LOAD_AVIALBLE_SEATS" 
export const GET_AVIALBLE_SEATS = "GET_AVIALBLE_SEATS"
export const FAILD_AVIALBLE_SEATS = "FAILD_AVIALBLE_SEATS"

// auth types 

export const LOAD_LOGIN = "LOAD_LOGIN"
export const SUCCESS_LOGIN = "SUCCESS_LOGIN"
export const FALID_LOGIN = "FALID_LOGIN"

export const LOAD_VERIFI_OTP = "LOAD_VERIFI_OTP"
export const SUCCESS_VERIFI_OTP = "SUCCESS_VERIFI_OTP"
export const FAIL_VERIFI_OTP = "FAIL_VERIFI_OTP"

export const LOAD_VALIDATE_OTP = "LOAD_VALIDATE_OTP"
export const SUCCESS_VALIDATE_OTP = "SUCCESS_VALIDATE_OTP"
export const FAIL_VALIDATE_OTP = "FAIL_VALIDATE_OTP"

export const LOAD_SEND_OTP = "LOAD_SEND_OTP"
export const SUCCESS_SEND_OTP = "SUCCESS_SEND_OTP"
export const FAIL_SEND_OTP = "FAIL_SEND_OTP"

export const LOAD_RESEND_OTP = "LOAD_RESEND_OTP"
export const SUCCESS_RESEND_OTP = "SUCCESS_RESEND_OTP"
export const FAIL_RESEND_OTP = "FAIL_RESEND_OTP"

export const LOGOUT = "LOGOUT"

