// types for bus travel 

export const LOAD_CITIES_SCCESSE = "LOAD_CITIES_SCCESSE"
export const GET_CITIES_SCCESSE = "GET_CITIES_SCCESSE"
export const FAILD_CITIES_SCCESSE = "FAILD_CITIES_SCCESSE"


export const LOAD_SEARCH = "LOAD_SEARCH"
export const GET_SEARCH = "GET_SEARCH"
export const FAILD_SEARCH = "FAILD_SEARCH"

export const LOAD_SINGLE_TRIP = "LOAD_SINGLE_TRIP" 
export const GET_SINGLE_TRIP = "GET_SINGLE_TRIP"
export const FAILD_SINGLE_TRIP = "FAILD_SINGLE_TRIP"

export const LOAD_AVIALBLE_SEATS = "LOAD_AVIALBLE_SEATS" 
export const GET_AVIALBLE_SEATS = "GET_AVIALBLE_SEATS"
export const FAILD_AVIALBLE_SEATS = "FAILD_AVIALBLE_SEATS"

// auth types 

export const LOAD_LOGIN = "LOAD_LOGIN"
export const SUCCESS_LOGIN = "SUCCESS_LOGIN"
export const FALID_LOGIN = "FALID_LOGIN"

export const LOAD_REGISTER = "LOAD_REGISTER"
export const SUCCESS_REGISTER = "SUCCESS_REGISTER"
export const FAIL_REGISTER = "FAIL_REGISTER"

export const LOAD_DELETE_ACC = "LOAD_DELETE_ACC"
export const SUCCESS_DELETE_ACC = "SUCCESS_DELETE_ACC"
export const FAIL_DELETE_ACC = "FAIL_DELETE_ACC"

export const LOAD_VERIFI_OTP = "LOAD_VERIFI_OTP"
export const SUCCESS_VERIFI_OTP = "SUCCESS_VERIFI_OTP"
export const FAIL_VERIFI_OTP = "FAIL_VERIFI_OTP"

export const LOAD_VALIDATE_OTP = "LOAD_VALIDATE_OTP"
export const SUCCESS_VALIDATE_OTP = "SUCCESS_VALIDATE_OTP"
export const FAIL_VALIDATE_OTP = "FAIL_VALIDATE_OTP"

export const LOAD_SEND_OTP = "LOAD_SEND_OTP"
export const SUCCESS_SEND_OTP = "SUCCESS_SEND_OTP"
export const FAIL_SEND_OTP = "FAIL_SEND_OTP"

export const LOAD_RESEND_OTP = "LOAD_RESEND_OTP"
export const SUCCESS_RESEND_OTP = "SUCCESS_RESEND_OTP"
export const FAIL_RESEND_OTP = "FAIL_RESEND_OTP"

export const LOGOUT = "LOGOUT"

// create ticket form bus trip  types 

export const LOAD_CREATE_TICKET = "LOAD_CREATE_TICKET"
export const SUCCESS_CREATE_TICKET = "SUCCESS_CREATE_TICKET"
export const FAIL_CREATE_TICKET = "FAIL_CREATE_TICKET"

export const LOAD_CREATE_RETURN_TICKET = "LOAD_CREATE_RETURN_TICKET"
export const SUCCESS_CREATE_RETURN_TICKET = "SUCCESS_CREATE_RETURN_TICKET"
export const FAIL_CREATE_RETURN_TICKET = "FAIL_CREATE_RETURN_TICKET"

// payment types 

export const LOAD_PAYMENT = 'LOAD_PAYMENT'
export const SUCCESS_PAYMENT = 'SUCCESS_PAYMENT'
export const FAIL_PAYMENT = 'FAIL_PAYMENT'

// profile types 

export const LOAD_PROFILE_TICKET = "LOAD_PROFILE_TICKET"
export const SUCCESS_PROFILE_TICKET = "SUCCESS_PROFILE_TICKET"
export const FAIL_PROFILE_TICKET = "FAIL_PROFILE_TICKET"

export const LOAD_CREATE_ADDRESS = "LOAD_CREATE_ADDRESS"
export const SUCCESS_CREATE_ADDRESS = "SUCCESS_CREATE_ADDRESS"
export const FAIL_CREATE_ADDRESS = "FAIL_CREATE_ADDRESS"

export const LOAD_GET_ADDRESS = "LOAD_GET_ADDRESS"
export const SUCCESS_GET_ADDRESS = "SUCCESS_GET_ADDRESS"
export const FAIL_GET_ADDRESS = "FAIL_GET_ADDRESS"

export const LOAD_DELETE_ADDRESS = "LOAD_DELETE_ADDRESS"
export const SUCCESS_DELETE_ADDRESS = "SUCCESS_DELETE_ADDRESS"
export const FAIL_DELETE_ADDRESS = "FAIL_DELETE_ADDRESS"

export const LOAD_UPDATE_ADDRESS = "LOAD_UPDATE_ADDRESS"
export const SUCCESS_UPDATE_ADDRESS = "SUCCESS_UPDATE_ADDRESS"
export const FAIL_UPDATE_ADDRESS = "FAIL_UPDATE_ADDRESS"

// type trip 

export const SET_TRIP_TYPE  = "SET_TRIP_TYPE "
